# Generated by Django 3.2.3 on 2022-08-08 12:26

import content.models.content
import content.utils.file_utils
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='date_created')),
                ('type', models.ForeignKey(default=content.models.content.ContentType.get_default_type_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='content.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='date_created')),
                ('file', models.FileField(upload_to=content.utils.file_utils.content_file_path)),
                ('father_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.content')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.library')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(default=content.models.content.ContentType.get_default_type_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='content.contenttype')),
            ],
        ),
    ]
