# Generated by Django 3.2.3 on 2022-08-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20220808_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.library'),
        ),
    ]
