# Generated by Django 3.2.3 on 2022-08-08 15:16

import content.utils.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20220808_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to=content.utils.file_utils.content_file_path),
        ),
    ]
