# Generated by Django 3.2.3 on 2022-08-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_library_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='info',
            field=models.CharField(default='{}', max_length=2000),
        ),
    ]
