# Generated by Django 3.2.3 on 2022-08-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_content_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(default='x', max_length=150),
            preserve_default=False,
        ),
    ]
