# Generated by Django 3.2.3 on 2022-08-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_content_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
